docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: v1/intro.md
site_name: 'http-client'
site_description: 'PSR-18 Http Client Utility'
repo_url: 'https://github.com/coisa/http-client'
