name: "Documentation"

on:
  push:
  release:
    types: [published]
  repository_dispatch:
    types: docs-build

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docs
        uses: laminas/documentation-theme/github-actions/docs@master
        with:
          siteUrl: https://coisa.github.io/http-client/
