name: docs-build

on:
  push:
  release:
    types: [published]
  repository_dispatch:
    types: docs-build

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docs
        uses: laminas/documentation-theme/github-actions/docs@master
