name: "Documentation"

on:
  push:
    branches: [master]

jobs:
  laminas-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Docs
        uses: laminas/documentation-theme/github-actions/docs@master
