name: "Documentation"

on:
  push:
  release:
    types: [published]
  repository_dispatch:
    types: docs-build

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docs
        uses: laminas/documentation-theme/github-actions/docs@master
        env:
          GITHUB_REF: master
        with:
          username: "github-actions[bot]"
          useremail: "41898282+github-actions[bot]@users.noreply.github.com"
          siteUrl: https://coisa.github.io/http-client/
