name: PHP
env:
  GITHUB_PAGES_BRANCH: coverage-report
on:
  push:
    branches-ignore:
      - $GITHUB_PAGES_BRANCH
jobs:
  build:
    strategy:
      matrix:
        php-version: [ '7.4', '8.0', '8.1' ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build & Push
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ github.repository }}:${{ matrix.php-version }}-${{ github.ref_name }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          buildargs: PHP_VERSION=${{ matrix.php-version }}

  analyse:
    needs: build

    strategy:
      matrix:
        php-version: [ '7.4', '8.0', '8.1' ]

    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}:${{ matrix.php-version }}-${{ github.ref_name }}

    steps:
      - name: PHPStan
        run: composer --working-dir=/usr/local/src run-script analyse

      - name: PHP Lint
        run: composer --working-dir=/usr/local/src run-script lint

  tests:
    needs: build

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1']

    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}:${{ matrix.php-version }}-${{ github.ref_name }}

    steps:
      - name: PHPUnit
        run: composer --working-dir=/usr/local/src run-script test

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: /usr/local/src/coverage

  deploy:
    needs: tests

    runs-on: ubuntu-latest

    steps:
      - name: Download Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - name: Deploy GitHub Pages
        run: |
          git config --global init.defaultBranch "$GITHUB_PAGES_BRANCH"

          git init
          git remote add origin ${{ github.repositoryUrl }}

          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          mv -v html/ docs/
          mv -v docs/_css/ docs/css/
          mv -v docs/_icons/ docs/icons/
          mv -v docs/_js/ docs/js/

          find docs -iname "*.html" -exec sed -i "s|_css|css|g" {} \;
          find docs -iname "*.html" -exec sed -i "s|_icons|icons|g" {} \;
          find docs -iname "*.html" -exec sed -i "s|_js|js|g" {} \;

          git update-ref -d HEAD
          git add docs/
          git commit -m "[Automation] Coverage Report ${GITHUB_RUN_NUMBER}"

          git push -f -u origin "$GITHUB_PAGES_BRANCH"
